### ISSUE TITLE
Global pattern not used for multiple loggers

### ISSUE THREAD

**Issue by hramoser** [guangie88/spdlog_setup#19]
Only the first logger uses global_pattern. Following loggers are assigned an empty pattern.
Reason: global_pattern_opt is moved instead of assigned (conf_impl.h, line 1113).

**Comment by guangie88** [comment]
Hey @hramoser, thanks for spotting this! Do you want to send a PR to fix this? I believe removing the `move` around `global_pattern_opt` should fix the issue. Would be better if you get the credit for spotting and fixing this :smiley:

**Comment by guangie88** [comment]
Resolved in #20. Thanks @hramoser for the PR!
