### ISSUE TITLE
CMake config uses wrong target name

### ISSUE THREAD

**Issue by jakecobb** [guangie88/spdlog_setup#21]
Version 2.0 but I glanced at master and it seems to have the same issue.  

`spdlog_setup-target.cmake` defines the `spdlog_setup::spdlog_setup` target, but `spdlog_setup-config.cmake` tries to reference the `spdlog_setup` target.  This causes an error for my `find_package` on CMake 3.9.2.  Manually editing `spdlog_setup-config.cmake` to reference `spdlog_setup::spdlog_setup` instead fixed it for me.

**Comment by guangie88** [comment]
Fixed by #22.
