### ISSUE TITLE
Compilation error: spdlog update?!

### ISSUE THREAD

**Issue by WarShoe** [guangie88/spdlog_setup#26]
Trying to compile spdlog_setup with the recent version (github) of spdlog:

`/usr/local/include/spdlog_setup/details/conf_impl.h:18:10: fatal error: spdlog/sinks/file_sinks.h: No such file or directory`

and yes, it looks that the file was renamed.

**Comment by LighthouseJ** [comment]
Found this myself just now when trying to use it.  You have to use pre-v1.x release of spdlog, like 0.17.0

**Comment by databuwa** [comment]
Would you kindly let me know when I could expect a spldlog_setup release which is compatible with latest spdlog.

**Comment by pwm1234** [comment]
I just made PR #27 that fixes the compilation errors I was encountering with spdlog_setup and a fairly current release of spdlog.

**Comment by PuneetPatwari** [comment]
Is there any hope of this update? It's very important one! @guangie88 please respond.

**Comment by guangie88** [comment]
Fix is on the way, the next PR will make it support `v1.y.z`, but not `v0.y.z` due to the breaking changes in `spdlog`, which is in this list [here](https://github.com/gabime/spdlog/releases/tag/v1.0.0). So for pre `v1.y.z`, please stick to `v0.2.0` as much as possible.

**Comment by guangie88** [comment]
PR merged, issue should be resolved. Please use tag release `v0.3.0-alpha.2` with the above fix.

Will close this if there are no more compatibility issues with `spdlog` `v1.y.z`

**Comment by PuneetPatwari** [comment]
Wow @guangie88 , you would not believe the appropriateness of this fix. In a day, I had to finalize my recommendation for a standard C++ log library and the lack of config file support in spdlog, I was forced to move to Boost.log. But this timely fix might just want me to stay with spdlog! Thanks a lot. I am going to explore if it fits my use case. 😄

**Comment by guangie88** [comment]
Closing this

**Comment by PuneetPatwari** [comment]
Hi @guangie88, things are working fine with the update. I wanted to know if in future you will still be maintaining this repo or not?

**Comment by guangie88** [comment]
@PuneetPatwari Will generally maintain this repo to be at least compilable with the `spdlog` `v1.y.z`.
