### ISSUE TITLE
Invalid Format String Error on using "from_file_with_tag_replacement()"

### ISSUE THREAD

**Issue by PuneetPatwari** [guangie88/spdlog_setup#30]
Hi @guangie88 , I am facing a strange problem while using the method "from_file_with_tag_replacement". I have written the following code

```
   try{
        const auto path_arg = fmt::arg("path", "log");
        spdlog_setup::from_file_with_tag_replacement(
            "log_conf.toml",
            path_arg
        );
        auto file_logger = spdlog::get("root");
        spdlog::set_default_logger(file_logger);
    }
    catch ( const spdlog_setup::setup_error err)
    {
        std::cout<<err.what();
    }
```
I get the output as `invalid format string`.

The config TOML file `log_conf.toml` looks like this

```
global_pattern = "{\"timestamp\"=\"%Y-%m-%d %H:%M:%S.%f %z\", \"logger\"=\"%n\", \"severity\"=\"%l\", \"file\"=\"%s\", \"line\"=\"%#\", \"message\"=\"%v\"}"

[[sink]]
name = "basic_logger"
type = "basic_file_sink_st"
filename = "{path}/spdlog_setup.log"
create_parent_dir = true

[[logger]]
name = "root"
sinks = ["basic_logger"]
level = "critical"
```

Please help me solve this problem. I have wasted a lot of time on this without much success.

**Comment by PuneetPatwari** [comment]
Hi @guangie88 Please help. I tried it with other machine as well. I get the same problem. Either I am doing something ridiculously silly mistake or is it something hidden! I have to show a demo of this usage today, please help.

**Comment by guangie88** [comment]
There is a bug in the way the current version of library parses the file for templating, i.e. `{xxx}` value, when we use `from_file_with_tag_replacement`. So the fastest way to resolve this is to just use this for global pattern first:

```
global_pattern = "timestamp\"=\"%Y-%m-%d %H:%M:%S.%f %z\", \"logger\"=\"%n\", \"severity\"=\"%l\", \"file\"=\"%s\", \"line\"=\"%#\", \"message\"=\"%v\""
```

If not, it also works if you use the plain `from_file` without the tag replacement.

I will resolve this at a later time.

**Comment by guangie88** [comment]
Alternatively, if you want to preserve the current string format, the way to print `{` or `}` is to escape it by doing `{{` and `}}`, as follow:

```
global_pattern = "{{\"timestamp\"=\"%Y-%m-%d %H:%M:%S.%f %z\", \"logger\"=\"%n\", \"severity\"=\"%l\", \"file\"=\"%s\", \"line\"=\"%#\", \"message\"=\"%v\"}}"
```

**Comment by PuneetPatwari** [comment]
Hi @guangie88, I am not facing a problem in my `global_pattern`. Please see the `[sink]` config where I have put `filename = {path}/log`. I was also able to run your unit_test.cpp but the tests failed for the pre-ToML use case.

**Comment by PuneetPatwari** [comment]
Hi @guangie88 , I am becoming very sure that there is a bug in the method `from_file_with_tag_replacement `. I was running your test cases and the `TEST_CASE(
    "Parse pre-TOML file for set-up", "[from_file_with_tag_replacement]")` passed successfully. However, when I changed the code `spdlog_setup::from_file_with_tag_replacement(tmp_file.get_file_path(), path_arg);` to

`spdlog_setup::from_file_with_tag_replacement("/Users/in-puneet.patwari/Downloads/log_conf.pre.toml", path_arg);` it immediately started to fail with the same error as above `invalid format string`. I urge you to kindly verify if this behaviour is true and there is a valid bug somewhere.

**Comment by PuneetPatwari** [comment]
> Alternatively, if you want to preserve the current string format, the way to print `{` or `}` is to escape it by doing `{{` and `}}`, as follow:
> 
> ```
> global_pattern = "{{\"timestamp\"=\"%Y-%m-%d %H:%M:%S.%f %z\", \"logger\"=\"%n\", \"severity\"=\"%l\", \"file\"=\"%s\", \"line\"=\"%#\", \"message\"=\"%v\"}}"
> ```

Hi @guangie88 , I understood what you meant to say now. I looked deep inside the codebase and realised that the gobal_pattern set by me with curly braces was the reason for the problem. Escaping it as suggested resolved the problem. Thanks again, and sorry for troubling with many questions.

**Comment by guangie88** [comment]
No problem, you might have already said it, the implementation is done with a `fmt` `format` function, so it requires the curly brackets to be escaped.

While it's not really a bug, I would say that the implementation is not really good and easy to encounter surprises like this, since all it takes is just a curly bracket to mess up the string. So I might look into using a more standard templating system such as `mustache` or `Jinja2`.

**Comment by PuneetPatwari** [comment]
Hi @guangie88 , I agree a small bracket wasted nearly 2 days of work. Pheww!! However, it feels good to explore in-depth and get to know more about the library. 

If in future, you port the library to support `mustache` or `jinja2`, it will result in a breaking change. I am about to recommend to our client the use of `spdlog` along with your library for C++ logging purpose in their applications. Do you see that as a problem? I guess you can keep separate branches maintaining the different templating system in your implementation.
